name: youtube_audio_downloader
description: A Flutter app to download and play audio from YouTube channels.
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path_provider_android: ^2.2.17
  flutter_local_notifications: ^19.3.1
  just_audio: ^0.10.4
  just_audio_background: ^0.0.1-beta.17
  http: ^1.4.0
  xml: ^6.5.0
  youtube_explode_dart:
    git: https://github.com/Coronon/youtube_explode_dart
  audio_service: ^0.18.12
  audio_session: ^0.2.2
  rxdart: ^0.28.0
  workmanager: ^0.8.0
  shared_preferences: ^2.2.2
  flutter_media_metadata: ^1.0.0
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/splash_logo.png

flutter_native_splash:
  color: "#D32F2F"
  image: assets/splash_logo.png
  android: true
  ios: true
  web: false

